services:
  ga_cf_planner:
    build: ./src/ga_cf_planner
    container_name: ga_cf_planner
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority
      - /sys/kernel/debug:/sys/kernel/debug
      - /proc/sys/kernel/perf_event_paranoid:/perf_event_paranoid:ro
      - ./src/ga_cf_planner:/ros2_ws
    stdin_open: true
    tty: true
    command: /bin/bash
    pid: host
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    init: true         
    privileged: true   