services:
  ga_cf_planner:
    build: ./src/ga_cf_planner
    container_name: ga_cf_planner
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority
      - ./src/ga_cf_planner:/ros2_ws
    stdin_open: true
    tty: true
    command: /bin/bash