name: percept_env
channels:
  - nvidia/label/cuda-12.8.0
  - conda-forge
  - defaults
dependencies:
# project-specific
  - python=3.10
  - cupy
  - numba
  - pyyaml
  - cuda-version=12.8
  - cudnn
  - cutensor
  - nccl
  - cuda-nvcc
# ros-specific
  - catkin_pkg
  - empy==3.3.4
  - lark-parser
  - spdlog
# data analysis
  - ipykernel
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - nbformat
  - tqdm
  - msgpack-python
  - msgpack-numpy
  - dash>=3.0.4
  - dash-bootstrap-components>=2.0.3
  - scikit-optimize
  - pip
  - pip:
      - transforms3d
      - cupoch