geometry_msgs/Pose agent_pose
geometry_msgs/Vector3 agent_velocity
geometry_msgs/Pose target_pose
float64 agent_radius
float64 detect_shell_rad
float64 k_force
float64 max_allowable_force
---
geometry_msgs/Vector3 circ_force
bool not_null